2019-07-03 17:57:28,125 [INFO ][org.jppf.utils.FileUtils.initJPPFTempDir(484)]: JPPF temp folder C:\Users\Administrator\AppData\Local\Temp\.jppf
2019-07-03 17:57:28,634 [INFO ][org.jppf.utils.VersionUtils.logVersionInformation(78)]: --------------------------------------------------------------------------------
2019-07-03 17:57:28,635 [INFO ][org.jppf.utils.VersionUtils.logVersionInformation(79)]: JPPF Version: 6.0.1, Build number: 2242, Build date: 2018-11-24 05:59 CET
2019-07-03 17:57:28,635 [INFO ][org.jppf.utils.VersionUtils.logVersionInformation(80)]: starting client with PID=10712, UUID=CD8ACBDD-DFC7-4F18-A4FA-44D03B7032AB
2019-07-03 17:57:28,635 [INFO ][org.jppf.utils.VersionUtils.logVersionInformation(81)]: --------------------------------------------------------------------------------
2019-07-03 17:57:28,647 [INFO ][org.jppf.persistence.DatasourceInitializerImpl.init(128)]: HikariCP libraries are not in the classpath, no datasource will be defined
2019-07-03 17:57:28,651 [INFO ][org.jppf.client.AbstractGenericClient.init(142)]: created client-side datasources: []
2019-07-03 17:57:28,680 [INFO ][org.jppf.load.balancer.persistence.LoadBalancerPersistenceManager.<init>(62)]: load-balancer persistence is not configured
2019-07-03 17:57:32,071 [INFO ][org.jppf.client.AbstractGenericClient.newConnection(263)]: connection [jppf_discovery-1-1] created
2019-07-03 17:57:33,125 [INFO ][org.jppf.client.ClassServerDelegateImpl.init(72)]: [client: jppf_discovery-1-1 - ClassServer] Attempting connection to the class server at 2WZ4K5OSTZRL1DR:11111
2019-07-03 17:57:33,132 [INFO ][org.jppf.client.ClassServerDelegateImpl.init(78)]: [client: jppf_discovery-1-1 - ClassServer] Reconnected to the class server
2019-07-03 17:57:33,168 [INFO ][org.jppf.client.TaskServerConnectionHandler.init(66)]: [client: jppf_discovery-1-1 - TasksServer] Attempting connection to the task server at 2WZ4K5OSTZRL1DR:11111
2019-07-03 17:57:33,215 [INFO ][org.jppf.client.TaskServerConnectionHandler.init(79)]: [client: jppf_discovery-1-1 - TasksServer] Reconnected to the JPPF task server
2019-07-03 17:57:33,252 [INFO ][org.jppf.nio.NioServer.<init>(145)]: initializing JMXNioServer(JMXRemote-1)
2019-07-03 17:57:33,265 [INFO ][org.jppf.nio.NioConstants.getCheckConnection(85)]: NIO checks are enabled
2019-07-03 18:09:48,651 [INFO ][org.jppf.client.JPPFClient.close(347)]: closing org.jppf.client.JPPFClient@f9b8bc
2019-07-03 18:09:48,652 [INFO ][org.jppf.client.AbstractGenericClient.close(305)]: closing JPPF client with uuid=CD8ACBDD-DFC7-4F18-A4FA-44D03B7032AB, PID=10712
